# Generated by Django 5.2.5 on 2025-08-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhraseContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='The word, phrase, or sentence in a Ugandan language.', max_length=500)),
                ('translation', models.CharField(blank=True, help_text='Optional English translation.', max_length=500, null=True)),
                ('language', models.CharField(choices=[('luganda', 'Luganda'), ('acholi', 'Acholi'), ('lugbara', 'Lugbara'), ('ateso', 'Ateso'), ('runyankole', 'Runyankole'), ('lusoga', 'Lusoga'), ('lumasaba', 'Lumasaba'), ('langi', 'Langi'), ('kakwa', 'Kakwa'), ('aluru', 'Aluru'), ('kumam', 'Kumam'), ('runyoro', 'Runyoro'), ('rukiga', 'Rukiga'), ('samia', 'Samia'), ('kinyarwanda', 'Kinyarwanda'), ('kupsapiiny', 'Kupsapiiny'), ('nyangore', 'Nyangore'), ('pokot', 'Pokot'), ('ik', 'Ik'), ('madu', 'Madu'), ('madi', 'Madi'), ("ma'di", "Ma'di"), ('ng`akaramojong', 'Ng`akaramojong'), ('sebei', 'Sebei'), ('sabiny', 'Sabiny'), ('suam', 'Suam'), ('chope', 'Chope'), ('nyakwai', 'Nyakwai'), ('soga', 'Soga'), ('ndyaba', 'Ndyaba'), ('ndyaba', 'Ndyaba'), ('ngboko', 'Ngboko'), ('kamba', 'Kamba'), ('amadi', 'Amadi'), ('sese', 'Sese'), ('talinga', 'Talinga'), ('nubi', 'Nubi'), ('kuku', 'Kuku'), ('kuliak', 'Kuliak'), ('ng`itome', 'Ng`itome'), ('ng`alimo', 'Ng`alimo'), ('elgon', 'Elgon')], help_text='The Ugandan language of the text.', max_length=50)),
                ('intent', models.CharField(choices=[('greeting', 'Greeting'), ('health', 'Health'), ('food', 'Food'), ('education', 'Education'), ('civic_tech', 'Civic Tech'), ('nature', 'Nature'), ('directions', 'Directions'), ('other', 'Other')], help_text='The intent or category of the text.', max_length=50)),
                ('contributor_name', models.CharField(blank=True, help_text='Optional name of the contributor.', max_length=100)),
                ('contributor_location', models.CharField(blank=True, help_text='Optional location of the contributor.', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_validated', models.BooleanField(default=False, help_text='Marks if the contribution has been reviewed and validated.')),
            ],
            options={
                'verbose_name': 'Phrase Contribution',
                'verbose_name_plural': 'Phrase Contributions',
                'ordering': ['-timestamp'],
            },
        ),
    ]
