# Generated by Django 5.2.5 on 2025-08-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrasecontribution',
            name='language',
            field=models.CharField(choices=[('luganda', 'Luganda'), ('lukenyi', 'Lukenyi'), ('acholi', 'Acholi'), ('lugbara', 'Lugbara'), ('ateso', 'Ateso'), ('runyankole', 'Runyankole'), ('lusoga', 'Lusoga'), ('lumasaba', 'Lumasaba'), ('langi', 'Langi'), ('kakwa', 'Kakwa'), ('aluru', 'Aluru'), ('kumam', 'Kumam'), ('runyoro', 'Runyoro'), ('rukiga', 'Rukiga'), ('samia', 'Samia'), ('kinyarwanda', 'Kinyarwanda'), ('kupsapiiny', 'Kupsapiiny'), ('nyangore', 'Nyangore'), ('pokot', 'Pokot'), ('ik', 'Ik'), ('madu', 'Madu'), ('madi', 'Madi'), ("ma'di", "Ma'di"), ('ng`akaramojong', 'Ng`akaramojong'), ('sebei', 'Sebei'), ('sabiny', 'Sabiny'), ('suam', 'Suam'), ('chope', 'Chope'), ('nyakwai', 'Nyakwai'), ('soga', 'Soga'), ('ndyaba', 'Ndyaba'), ('ndyaba', 'Ndyaba'), ('ngboko', 'Ngboko'), ('kamba', 'Kamba'), ('amadi', 'Amadi'), ('sese', 'Sese'), ('talinga', 'Talinga'), ('nubi', 'Nubi'), ('kuku', 'Kuku'), ('kuliak', 'Kuliak'), ('ng`itome', 'Ng`itome'), ('ng`alimo', 'Ng`alimo'), ('elgon', 'Elgon')], help_text='The Ugandan language of the text.', max_length=50),
        ),
    ]
