# Generated by Django 5.2.5 on 2025-08-24 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_alter_phrasecontribution_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the contributor.', max_length=100, unique=True)),
                ('location', models.CharField(blank=True, help_text='The location of the contributor.', max_length=100)),
                ('badge', models.CharField(default='New Contributor', help_text='The badge earned by the contributor.', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='phrasecontribution',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='phrasecontribution',
            name='contributor_location',
            field=models.CharField(blank=True, help_text='The location of the contributor.', max_length=100),
        ),
        migrations.AlterField(
            model_name='phrasecontribution',
            name='contributor_name',
            field=models.CharField(blank=True, help_text='The name of the contributor.', max_length=100),
        ),
        migrations.AlterField(
            model_name='phrasecontribution',
            name='intent',
            field=models.CharField(choices=[('greetings', 'Greetings & Courtesies'), ('travel', 'Travel & Directions'), ('food', 'Food & Dining'), ('culture', 'Culture & Traditions'), ('emergency', 'Emergency Phrases'), ('business', 'Business & Commerce'), ('medical', 'Medical & Health'), ('education', 'Education'), ('family', 'Family & Relationships'), ('technology', 'Technology & Modern Life'), ('expressions', 'Common Expressions & Idioms'), ('questions', 'Questions'), ('statements', 'Statements')], help_text='The intent or category of the text.', max_length=50),
        ),
        migrations.AlterField(
            model_name='phrasecontribution',
            name='language',
            field=models.CharField(choices=[('luganda', 'Luganda'), ('acholi', 'Acholi'), ('lugbara', 'Lugbara'), ('ateso', 'Ateso'), ('runyankole', 'Runyankole'), ('lusoga', 'Lusoga'), ('lumasaba', 'Lumasaba'), ('langi', 'Langi'), ('kakwa', 'Kakwa'), ('aluru', 'Aluru'), ('kumam', 'Kumam'), ('runyoro', 'Runyoro'), ('rukiga', 'Rukiga'), ('samia', 'Samia'), ('kinyarwanda', 'Kinyarwanda'), ('kupsapiiny', 'Kupsapiiny'), ('nyangore', 'Nyangore'), ('pokot', 'Pokot'), ('ik', 'Ik'), ('madu', 'Madu'), ('madi', 'Madi'), ("ma'di", "Ma'di"), ('ng`akaramojong', 'Ng`akaramojong'), ('sebei', 'Sebei'), ('sabiny', 'Sabiny'), ('suam', 'Suam'), ('chope', 'Chope')], help_text='The Ugandan language of the text.', max_length=50),
        ),
        migrations.AddField(
            model_name='phrasecontribution',
            name='contributor',
            field=models.ForeignKey(blank=True, help_text='The contributor associated with this phrase.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='languages.contributor'),
        ),
    ]
