# Generated by Django 5.2.5 on 2025-08-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0003_contributor_phrasecontribution_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrasecontribution',
            name='language',
            field=models.CharField(choices=[('luganda', 'Luganda'), ('lusoga', 'Lusoga'), ('lugwere', 'Lugwere'), ('lumasaba', 'Lumasaba'), ('samia', 'Samia'), ('chope', 'Chope'), ('lukenye', 'Lukenye'), ('runyankole', 'Runyankole'), ('rukiga', 'Rukiga'), ('runyoro', 'Runyoro'), ('rutooro', 'Rutooro'), ('runyakitara', 'Runyakitara'), ('kinyarwanda', 'Kinyarwanda'), ('lussese', 'Lussese'), ('acholi', 'Acholi'), ('alur', 'Alur'), ('langi', 'Langi'), ('ateso', 'Ateso'), ('kupsapiiny', 'Kupsapiiny'), ('sabiny', 'Sabiny'), ('sebei', 'Sebei'), ('suam', 'Suam'), ('pokot', 'Pokot'), ('ik', 'Ik'), ('kumam', 'Kumam'), ('luo', 'Luo'), ('adhola', 'Adhola'), ('lugbara', 'Lugbara'), ('madi', 'Madi'), ("ma'di", "Ma'di"), ('madu', 'Madu'), ('kakwa', 'Kakwa'), ('nyangore', 'Nyangore'), ('sw', 'Swahili'), ('ar', 'Arabic'), ('ber', 'Berber'), ('tzm', 'Tamazight'), ('am', 'Amharic'), ('om', 'Oromo'), ('ti', 'Tigrinya'), ('so', 'Somali'), ('sw', 'Swahili'), ('rw', 'Kinyarwanda'), ('rn', 'Kirundi'), ('ss', 'Swati'), ('mg', 'Malagasy'), ('ln', 'Lingala'), ('kg', 'Kongo'), ('frc', 'French (Central Africa)'), ('sg', 'Sango'), ('ha', 'Hausa'), ('yo', 'Yoruba'), ('ig', 'Igbo'), ('ff', 'Fula'), ('tw', 'Twi'), ('ee', 'Ewe'), ('bm', 'Bambara'), ('wo', 'Wolof'), ('kp', 'Kpelle'), ('kr', 'Kanuri'), ('zu', 'Zulu'), ('xh', 'Xhosa'), ('sn', 'Shona'), ('nd', 'Ndebele'), ('ts', 'Tsonga'), ('tn', 'Tswana'), ('ve', 'Venda'), ('ss', 'Swati'), ('afr', 'Afrikaans'), ('nso', 'Northern Sotho'), ('st', 'Southern Sotho'), ('dib', 'Dinka'), ('ach', 'Acholi'), ('lug', 'Luganda'), ('run', 'Runyankore'), ('kin', 'Kinyankole'), ('kam', 'Kamba'), ('kik', 'Kikuyu'), ('ny', 'Chichewa'), ('bem', 'Bemba'), ('loz', 'Lozi'), ('tsn', 'Tswana'), ('swa', 'Swahili'), ('zul', 'Zulu'), ('xho', 'Xhosa'), ('sot', 'Sotho'), ('ven', 'Venda'), ('twi', 'Twi'), ('ibo', 'Igbo'), ('yor', 'Yoruba'), ('hau', 'Hausa'), ('ful', 'Fula')], help_text='The Ugandan language of the text.', max_length=50),
        ),
    ]
