# Generated by Django 5.2.8 on 2025-11-22 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0004_alter_phrasecontribution_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the applicant/recruiter.', max_length=100, unique=True)),
                ('location', models.CharField(blank=True, help_text="The applicant's (Recruiter's) primary location.", max_length=100)),
                ('endorsement_status', models.CharField(default='New Recruiter', help_text='The professional endorsement status earned.', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='phrasecontribution',
            name='contributor',
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_content', models.CharField(help_text='The job description or application detail.', max_length=500)),
                ('required_skills', models.CharField(blank=True, help_text='Optional: Required skills or applicant bio.', max_length=500, null=True)),
                ('job_category', models.CharField(choices=[('luganda', 'Information Technology'), ('lusoga', 'Software Development'), ('lugwere', 'Data Science & AI'), ('lumasaba', 'Cyber Security'), ('samia', 'Cloud Engineering'), ('runyankole', 'Finance & Accounting'), ('rukiga', 'Marketing & Sales'), ('runyoro', 'Human Resources'), ('rutooro', 'Supply Chain & Logistics'), ('runyakitara', 'Project Management'), ('kinyarwanda', 'Creative Design'), ('acholi', 'Customer Support'), ('alur', 'Healthcare & Pharma'), ('ateso', 'Education & Training'), ('sw', 'General Management'), ('chope', 'Manufacturing'), ('lukenye', 'Telecommunications'), ('lussese', 'Real Estate'), ('langi', 'Government/Public Sector'), ('kupsapiiny', 'Energy & Utilities'), ('sabiny', 'Legal Services'), ('sebei', 'Agriculture'), ('suam', 'NGO/Non-Profit'), ('pok', 'Consulting')], help_text='The professional category of the job.', max_length=50)),
                ('job_type', models.CharField(choices=[('greetings', 'Full-Time'), ('travel', 'Part-Time'), ('food', 'Contract/Freelance'), ('culture', 'Internship'), ('emergency', 'Urgent Hire'), ('business', 'Remote'), ('medical', 'Entry-Level'), ('education', 'Senior/Expert'), ('family', 'Executive'), ('technology', 'Consulting'), ('expressions', 'Short-Term Project'), ('questions', 'Graduate Trainee'), ('statements', 'Volunteer Position')], help_text='The type of employment (e.g., Full-Time, Contract).', max_length=50)),
                ('recruiter_name', models.CharField(blank=True, help_text='The name of the recruiter/posting company.', max_length=100)),
                ('recruiter_location', models.CharField(blank=True, help_text='The location of the company/recruiter.', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_validated', models.BooleanField(default=False, help_text='Marks if the job post has been reviewed and validated.')),
                ('upvotes', models.IntegerField(default=0)),
                ('applicant', models.ForeignKey(blank=True, help_text='The Applicant (Recruiter) associated with this job post.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='languages.applicant')),
            ],
            options={
                'verbose_name': 'Job Post',
                'verbose_name_plural': 'Job Posts',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='Contributor',
        ),
        migrations.DeleteModel(
            name='PhraseContribution',
        ),
    ]
