# Generated by Django 5.2.8 on 2025-11-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0005_applicant_remove_phrasecontribution_contributor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicant',
            options={'ordering': ['-total_posts', 'name'], 'verbose_name': 'Applicant (Recruiter)', 'verbose_name_plural': 'Applicants (Recruiters)'},
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='endorsement_status',
        ),
        migrations.AddField(
            model_name='applicant',
            name='total_posts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='company_logo_or_media',
            field=models.FileField(blank=True, help_text='Optional: Upload a company logo (image) or short recruitment video.', null=True, upload_to='job_media/'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_category',
            field=models.CharField(choices=[('luganda', 'Information Technology'), ('lusoga', 'Software Development'), ('lugwere', 'Data Science & AI'), ('lumasaba', 'Cyber Security'), ('samia', 'Cloud Engineering'), ('runyankole', 'Finance & Accounting'), ('rukiga', 'Marketing & Sales'), ('runyoro', 'Human Resources'), ('rutooro', 'Supply Chain & Logistics'), ('runyakitara', 'Project Management'), ('kinyarwanda', 'Creative Design'), ('acholi', 'Customer Support'), ('alur', 'Healthcare & Pharma'), ('ateso', 'Education & Training'), ('sw', 'General Management'), ('chope', 'Manufacturing'), ('lukenye', 'Telecommunications'), ('lussese', 'Real Estate'), ('langi', 'Government/Public Sector'), ('kupsapiiny', 'Energy & Utilities'), ('sabiny', 'Legal Services'), ('sebei', 'Agriculture'), ('suam', 'NGO/Non-Profit'), ('pokot', 'Hospitality/Travel')], help_text='The professional category of the job.', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_type',
            field=models.CharField(choices=[('ft', 'Full-Time'), ('pt', 'Part-Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('remote', 'Remote')], help_text='The type of employment (e.g., Full-Time, Contract).', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='post_content',
            field=models.TextField(help_text='The main content of the job post.'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='required_skills',
            field=models.TextField(blank=True, default='Skills not provided', help_text='Optional: Key required skills or qualifications.'),
            preserve_default=False,
        ),
    ]
