# Generated by Django 5.2.8 on 2025-11-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0006_alter_applicant_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicant',
            options={'verbose_name': 'Recruiter', 'verbose_name_plural': 'Recruiters'},
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='name',
            new_name='recruiter_name',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='location',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='application_url',
            field=models.URLField(blank=True, help_text='The direct link where applicants can apply for this job (e.g., Company career page, LinkedIn, or email).', null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_category',
            field=models.CharField(choices=[('luganda', 'Information Technology'), ('lusoga', 'Software Development'), ('lugwere', 'Data Science & AI'), ('lumasaba', 'Cyber Security'), ('samia', 'Cloud Engineering'), ('runyankole', 'Finance & Accounting'), ('rukiga', 'Marketing & Sales'), ('runyoro', 'Human Resources'), ('rutooro', 'Supply Chain & Logistics'), ('runyakitara', 'Project Management'), ('kinyarwanda', 'Creative Design'), ('acholi', 'Customer Support'), ('alur', 'Healthcare & Pharma'), ('ateso', 'Education & Training'), ('sw', 'General Management'), ('chope', 'Manufacturing'), ('lukenye', 'Telecommunications'), ('lussese', 'Real Estate'), ('langi', 'Government/Public Sector'), ('kupsapiiny', 'Energy & Utilities'), ('sabiny', 'Legal Services'), ('sebei', 'Agriculture'), ('suam', 'NGO/Non-Profit'), ('pokot', 'Hospitality/Travel')], default='luganda', help_text='Select the industry/category for this job.', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_type',
            field=models.CharField(choices=[('fulltime', 'Full-Time'), ('parttime', 'Part-Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('freelance', 'Freelance')], default='fulltime', help_text='Select the type of employment.', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='post_content',
            field=models.TextField(help_text='The full description of the job.'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='required_skills',
            field=models.TextField(help_text='List the essential skills and qualifications.'),
        ),
    ]
