# Generated by Django 5.2.8 on 2025-12-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0007_alter_applicant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
