# Generated by Django 5.2.8 on 2025-12-05 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0008_applicant_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='recruiter_email',
            field=models.EmailField(blank=True, help_text="The email address applicants should use for 'Easy Apply'.", max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='recruiter_whatsapp',
            field=models.CharField(blank=True, help_text="The WhatsApp number (e.g., +256701234567) applicants should use for 'Easy Apply'.", max_length=20, null=True),
        ),
    ]
