# Generated by Django 5.2.8 on 2025-12-21 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0009_jobpost_recruiter_email_jobpost_recruiter_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='is_validated',
            field=models.BooleanField(default=True, help_text='Marks if the job post has been reviewed and validated.'),
        ),
    ]
