# Generated by Django 6.0.1 on 2026-01-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0010_alter_jobpost_is_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='click_count',
            field=models.PositiveIntegerField(default=0, help_text='Tracks outbound clicks to monitor PPC revenue performance.'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='external_source',
            field=models.CharField(blank=True, db_index=True, help_text='The name of the partner (e.g., Adzuna, Monday).', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='is_external',
            field=models.BooleanField(db_index=True, default=False, help_text='True if this job is backfilled from an external partner API (e.g., Adzuna).'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='application_url',
            field=models.URLField(blank=True, help_text='The direct link where applicants can apply for this job.', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['is_external', 'job_category'], name='languages_j_is_exte_c1d57d_idx'),
        ),
    ]
