# Generated by Django 6.0.1 on 2026-01-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0011_jobpost_click_count_jobpost_external_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='external_source',
            field=models.CharField(blank=True, db_index=True, help_text='The name of the partner (e.g., Adzuna, Careerjet).', max_length=50, null=True),
        ),
    ]
