# Generated by Django 5.2.13 on 2026-05-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0012_alter_jobpost_external_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='base_salary',
            field=models.CharField(blank=True, help_text="Base salary range or amount (e.g., '$50,000 - $70,000 per year').", max_length=100),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_location_address',
            field=models.CharField(blank=True, help_text='Full address for job location (required for Google structured data).', max_length=255),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='valid_through',
            field=models.DateTimeField(blank=True, help_text='Expiration date for the job posting (required for Google structured data).', null=True),
        ),
    ]
