# Generated by Django 5.0.6 on 2026-09-30 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0015_jobpost_posted_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_query', models.CharField(blank=True, max_length=120)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('category', models.CharField(blank=True, choices=[('luganda', 'Information Technology'), ('lusoga', 'Software Development'), ('lugwere', 'Data Science & AI'), ('lumasaba', 'Cyber Security'), ('samia', 'Cloud Engineering'), ('runyankole', 'Finance & Accounting'), ('rukiga', 'Marketing & Sales'), ('runyoro', 'Human Resources'), ('rutooro', 'Supply Chain & Logistics'), ('runyakitara', 'Project Management'), ('kinyarwanda', 'Creative Design'), ('acholi', 'Customer Support'), ('alur', 'Healthcare & Pharma'), ('ateso', 'Education & Training'), ('sw', 'General Management'), ('chope', 'Manufacturing'), ('lukenye', 'Telecommunications'), ('lussese', 'Real Estate'), ('langi', 'Government/Public Sector'), ('kupsapiiny', 'Energy & Utilities'), ('sabiny', 'Legal Services'), ('sebei', 'Agriculture'), ('suam', 'NGO/Non-Profit'), ('pokot', 'Hospitality/Travel')], default='', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobAlertDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='languages.jobalert')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_deliveries', to='languages.jobpost')),
            ],
        ),
        migrations.AddConstraint(
            model_name='jobalert',
            constraint=models.UniqueConstraint(fields=('user', 'role_query', 'location', 'category'), name='unique_user_job_alert_search'),
        ),
        migrations.AddConstraint(
            model_name='jobalertdelivery',
            constraint=models.UniqueConstraint(fields=('alert', 'job'), name='unique_job_alert_delivery'),
        ),
    ]
