# Generated by Django 5.0.6 on 2026-09-23 16:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30)),
                ('whatsapp_phone', models.CharField(blank=True, max_length=30)),
                ('vehicle_type', models.CharField(choices=[('standard', 'Standard car'), ('comfort', 'Comfort car'), ('boda', 'Boda')], default='standard', max_length=20)),
                ('vehicle_make', models.CharField(blank=True, max_length=80)),
                ('vehicle_plate', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending verification'), ('verified', 'Verified'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('is_available', models.BooleanField(default=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('last_location_at', models.DateTimeField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=5, max_digits=3)),
                ('completed_trips', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_landmark', models.CharField(max_length=255)),
                ('dropoff_landmark', models.CharField(max_length=255)),
                ('pickup_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('pickup_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('dropoff_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('dropoff_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('ride_type', models.CharField(choices=[('standard', 'Standard ride'), ('comfort', 'Comfort ride'), ('boda', 'Boda ride')], default='standard', max_length=20)),
                ('payment_method', models.CharField(choices=[('momo', 'Mobile Money'), ('cash', 'Cash'), ('card', 'Card')], default='momo', max_length=20)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('matching', 'Matching'), ('assigned', 'Driver assigned'), ('arrived', 'Driver arrived'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('estimated_fare_min', models.PositiveIntegerField()),
                ('estimated_fare_max', models.PositiveIntegerField()),
                ('distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('eta_minutes', models.PositiveIntegerField(default=10)),
                ('cancellation_reason', models.CharField(blank=True, max_length=255)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides', to='logistics.driverprofile')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='RideRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_ride_ratings', to='logistics.driverprofile')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_ride_ratings', to=settings.AUTH_USER_MODEL)),
                ('ride', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating_record', to='logistics.riderequest')),
            ],
        ),
        migrations.CreateModel(
            name='RidePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('momo', 'MTN MoMo'), ('airtel', 'Airtel Money'), ('card', 'Card'), ('cash', 'Cash')], max_length=20)),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('provider_transaction_id', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ride', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='logistics.riderequest')),
            ],
        ),
        migrations.CreateModel(
            name='RideLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('accuracy_meters', models.PositiveIntegerField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_pings', to='logistics.driverprofile')),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='logistics.riderequest')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='SafetyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('emergency', 'Emergency'), ('unsafe_driving', 'Unsafe driving'), ('lost_item', 'Lost item'), ('other', 'Other')], max_length=30)),
                ('details', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewing', 'Reviewing'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_reports', to=settings.AUTH_USER_MODEL)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_reports', to='logistics.riderequest')),
            ],
        ),
    ]
