# Generated by Django 5.0.6 on 2026-09-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_supportticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderequest',
            name='payment_method',
            field=models.CharField(choices=[('momo', 'Mobile Money'), ('airtel', 'Airtel Money'), ('cash', 'Cash'), ('card', 'Card')], default='momo', max_length=20),
        ),
    ]
