# Generated by Django 5.2.8 on 2025-11-23 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name'], 'verbose_name_plural': 'Skills'},
        ),
        migrations.AddField(
            model_name='education',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='customuser_set', related_query_name='customuser', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customuser_permissions_set', related_query_name='customuser_permission', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='SocialConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn (Professional)'), ('github', 'GitHub (Developer)'), ('portfolio', 'Personal Portfolio'), ('x', 'X / Twitter'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('medium', 'Medium / Blog')], max_length=50)),
                ('url', models.URLField(help_text='The full URL to your profile.', max_length=500)),
                ('access_token', models.CharField(blank=True, help_text='OAuth token for API access (managed by system).', max_length=512, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Social Connection',
                'verbose_name_plural': 'Social Connections',
                'unique_together': {('user', 'platform')},
            },
        ),
    ]
