# Generated by Django 6.0.4 on 2026-04-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='language',
            field=models.CharField(default='en', help_text="User's preferred language for content, e.g., 'en', 'sw', 'fr'", max_length=10, verbose_name='Preferred Language'),
        ),
    ]
