# Generated by Django 5.0.6 on 2026-04-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Whether this investor account is approved to post partner content.', verbose_name='Is Approved'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('regular', 'Regular User'), ('investor', 'Investor')], default='regular', help_text='Type of user account.', max_length=20, verbose_name='User Type'),
        ),
    ]
