# Generated by Django 5.0.6 on 2026-09-07 16:21

import django.db.models.functions.text
from django.db import migrations, models


def remove_duplicate_names(apps, schema_editor):
    event_booking = apps.get_model('users', 'EventBooking')
    seen_names = set()
    duplicate_ids = []
    for booking in event_booking.objects.order_by('id').only('id', 'full_name'):
        normalized_name = booking.full_name.strip().casefold()
        if normalized_name in seen_names:
            duplicate_ids.append(booking.id)
        else:
            seen_names.add(normalized_name)
    if duplicate_ids:
        event_booking.objects.filter(id__in=duplicate_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_eventbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbooking',
            name='founding_member_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.RunPython(remove_duplicate_names, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='eventbooking',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('full_name'), name='unique_event_booking_full_name_ci'),
        ),
    ]
