# Generated by Django 5.0.6 on 2026-09-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_eventbooking_founding_member_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='allow_channel_invites',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='direct_message_privacy',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('connections', 'Accepted connections only'), ('nobody', 'Nobody')], default='everyone', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='discoverable_by_handle',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='show_online_status',
            field=models.BooleanField(default=True),
        ),
    ]
