"""
Django settings for myuganda project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
from django.urls import reverse_lazy
import dj_database_url # Import the dj_database_url library
# Cloudinary imports
import cloudinary
import cloudinary_storage

# NEW: Import the library to load environment variables from .env
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# NEW: Load environment variables from the .env file
# This must be done before any os.environ.get() calls
load_dotenv(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-(p31q0!)f868y09ivx%&d&jjc&^jenjy6p2ozj%3pijiwm_2=f')

# SECURITY WARNING: don't run with debug turned on in production!
# Set DEBUG to False in production
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# Use environment variable for allowed hosts, falling back to a wildcard for flexibility.
# In Render, you would set the DJANGO_ALLOWED_HOSTS environment variable.
ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', '*').split(',')

# --- PRODUCTION FIXES FOR CSRF & PROXY SSL ---

# 1. Configure the Proxy Header
# Koyeb uses a reverse proxy. This setting tells Django to trust the 'X-Forwarded-Proto' 
# header, ensuring Django knows the connection is HTTPS, which is required for secure cookies 
# and CSRF to function correctly in production.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# 2. Configure trusted origins for CSRF protection
# The primary cause of CSRF failure in production is a missing or incorrect domain in trusted origins.

# The full hostname of your Koyeb deployment
KOYEB_HOST = 'initial-danette-africana-60541726.koyeb.app'

# List of all hosts to be trusted for CSRF
TRUSTED_HOSTS = [
    KOYEB_HOST,
]

# Add hosts from the ALLOWED_HOSTS environment variable
hosts_from_env = os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',')
for host in hosts_from_env:
    # Add any allowed host that is not a wildcard
    if host.strip() and host.strip() != '*' and host.strip() not in TRUSTED_HOSTS:
        TRUSTED_HOSTS.append(host.strip())

# Construct CSRF_TRUSTED_ORIGINS by adding the HTTPS scheme to all trusted hosts.
# This is necessary because the browser sends the full origin.
CSRF_TRUSTED_ORIGINS = [f'https://{host}' for host in TRUSTED_HOSTS]

# Explicitly add local development origins (http)
CSRF_TRUSTED_ORIGINS.extend([
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    'http://127.0.0.1',
    'http://localhost',
])
# Note: Removed the redundant 'https://initial-danette-africana-60541726.koyeb.app/' 
# entry since it is already covered above and the trailing slash is incorrect.

# --- END PRODUCTION FIXES ---


# Application definition

INSTALLED_APPS = [
    # Jazzmin Admin Interface
    'users',
    'jazzmin',
    'django.contrib.admin',
    
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'django.contrib.sites',  # required for sitemaps

    
    # NEW FIX: Add django.contrib.humanize for template tags like 'intcomma'
    'django.contrib.humanize', 

    # Third-party apps
    'widget_tweaks',
    'cloudinary_storage',
    'cloudinary',

    # My Apps (FIX: added 'languages' for Model lookup)
    'eshop',
    'languages', 
]

SITE_ID = 1


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myuganda.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myuganda.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# Use dj_database_url to parse the DATABASE_URL environment variable
# for easy deployment setup (e.g., on Render or Heroku)
DATABASE_URL = os.environ.get("DATABASE_URL")

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.config(default=DATABASE_URL, conn_max_age=600)
    }
else:
    # Fallback to SQLite for local development if DATABASE_URL is not set
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# --- Custom Authentication Configuration ---
AUTH_USER_MODEL = 'users.CustomUser' 

# Directs unauthenticated requests to your custom view
LOGIN_URL = reverse_lazy('users:user_login')

# The URL to redirect to after a user successfully logs in
LOGIN_REDIRECT_URL = reverse_lazy('languages:browse_job_listings')

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/ref/settings/#staticfiles

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

MEDIA_URL = '/media/'
# When CLOUDINARY_STORAGE is enabled, files will be uploaded there
MEDIA_ROOT = os.path.join(BASE_DIR, 'media') 


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Cloudinary Configuration
# Ensure these are set in your .env file or environment variables
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY'),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET'),
}

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'


# Gemini API Key (for the AI Negotiation feature)
# Ensure this is set in your .env file or environment variables
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")


# settings.py (REVISED JAZZMIN_SETTINGS)

JAZZMIN_SETTINGS = {
    # --- Branding (Kept as-is) ---
    "site_title": "Uganda Admin", 
    "site_header": "Uganda",      
    "site_brand": "Uganda",       
    "site_logo": "static/images/uganda_logo.png", 
    "site_icon": "static/images/favicon.ico",
    "welcome_sign": "Welcome to Uganda — Administration Dashboard", 
    "user_avatar": None,
    
    # --- Menu Structure ---
    "search_model": ["users.CustomUser", "eshop.Product", "languages.PhraseContribution"],
    
    # HIDE unnecessary Top Menu links for a cleaner header
    "topmenu_links": [
        {"name": "Dashboard", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"model": "users.CustomUser"},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    
    # --- Side Menu Links ---
    "usermenu_links": [
        {"name": "See Profile", "url": "/profile/", "icon": "fas fa-user-circle"},
    ],
    
    # Custom Links (Refined Grouping)
    "custom_links": {
        "languages": [
            {
                "name": "Job Management",
                "icon": "fas fa-briefcase",
                # Group JobPost, Recruiter, JobCategory, JobType
                "models": ["languages.JobPost", "languages.Recruiter", "languages.JobCategory", "languages.JobType"],
            },
            {
                "name": "Phrase Contributions",
                "icon": "fas fa-language",
                # Group PhraseContribution
                "models": ["languages.PhraseContribution"],
            },
        ],
        "eshop": [
            {
                "name": "Store Operations",
                "icon": "fas fa-store",
                # Group Product and Order
                "models": ["eshop.Product", "eshop.Order"],
            },
        ],
    },
    
    # --- Hiding Redundant/System Models (Simplified) ---
    # Only hide system models and the apps that hold only grouped models.
    "hide_apps": ["contenttypes", "sessions", "sites", "cloudinary_storage", "cloudinary"],
    
    # Only hide the individual models that are now grouped under "custom_links"
    "hide_models": [
        "languages.JobPost", "languages.Recruiter", "languages.JobCategory", "languages.JobType", "languages.PhraseContribution",
        "eshop.Product", "eshop.Order", 
        "auth.Group" # Hiding Group since permissions are managed via Users
    ],


    # Ordering apps in the menu
    "order_with_respect_to": ["auth", "users", "eshop", "languages"],
    "related_modal_active": False,

    # --- Icons (Retained and used for custom links) ---
    "icons": {
        "auth": "fas fa-shield-alt",
        "auth.user": "fas fa-user",
        "users.CustomUser": "fas fa-user-circle",
        # ... (rest of the icons are fine)
        "eshop.Product": "fas fa-box-open",
        "eshop.Order": "fas fa-shopping-cart",
        "languages.JobPost": "fas fa-file-alt",
        "languages.Recruiter": "fas fa-address-card",
        "languages.JobCategory": "fas fa-sitemap",
        "languages.JobType": "fas fa-clock",
        "languages.PhraseContribution": "fas fa-language",
    },
    "default_icon_parents": "fas fa-folder-open",
    "default_icon_children": "fas fa-circle",
}


# settings.py (REVISED JAZZMIN_UI_TWEAKS)
JAZZMIN_UI_TWEAKS = {
    # --- Theme & Colors (Kept as-is) ---
    "theme": "lux",                     
    "dark_mode_theme": "darkly",        
    "accent": "accent-primary",
    "navbar": "navbar-dark navbar-primary", 
    "sidebar": "sidebar-dark-primary",     

    # --- Layout Organization Fixes (Essential for a clean, compact look) ---
    "navbar_fixed": True,              
    "sidebar_fixed": True,              
    "sidebar_nav_child_indent": True,  
    "footer_small_text": True,          
    "layout_boxed": False, 
    
    # TWEAKS RELAXED FOR CLARITY:
    "navbar_small_text": True,          # Still useful for a sleek top bar
    "body_small_text": False,           # **CRITICAL CHANGE**: Use default body text size
    "sidebar_nav_compact_style": False, # **CRITICAL CHANGE**: Use normal sidebar spacing
    "sidebar_nav_small_text": False,    # **CRITICAL CHANGE**: Use normal sidebar text size

    # --- Button Styles (Kept as-is) ---
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    "actions_button_classes": {
        "add": "btn-success",
        "change": "btn-info",
        "delete": "btn-danger",
        "save": "btn-primary",
        "submit": "btn-primary",
    },
    
    # --- Other Layout Settings (retained/optimized) ---
    "brand_small_text": False,
    "no_navbar_border": False,
    "footer_fixed": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
}