# Generated by Django 6.0.2 on 2026-03-07 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Movie Title')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(verbose_name='Plot Summary')),
                ('ai_summary', models.TextField(blank=True, help_text='AI-generated catchy summary', null=True)),
                ('ai_recommendation_tags', models.CharField(blank=True, help_text='AI keywords', max_length=500)),
                ('genre', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('image_url', models.TextField(help_text='Direct URL for movie posters')),
                ('trailer_url', models.URLField(blank=True, null=True)),
                ('affiliate_url', models.TextField(help_text='Link to watch on Amazon/Netflix')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('view_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='Redirected', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
            ],
        ),
    ]
