# Generated by Django 6.0.3 on 2026-03-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('trending', 'Trending'), ('new', 'New Release'), ('date_night', 'Date Night')], default='new', max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='affiliate_url',
            field=models.TextField(help_text='Link to watch on Amazon/Netflix/Disney+'),
        ),
    ]
