# Generated by Django 5.0.6 on 2026-05-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_add_message_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitymessage',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
