# Generated by Django 5.0.6 on 2026-09-19 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_feedimpression'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='communitymessage',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='communitymessage',
            name='moderation_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='communitymessage',
            name='moderation_status',
            field=models.CharField(choices=[('visible', 'Visible'), ('held', 'Held'), ('rejected', 'Rejected')], default='visible', max_length=10),
        ),
        migrations.AddField(
            model_name='communitymessage',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='hotel.communitymessage'),
        ),
        migrations.CreateModel(
            name='CommunityChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(max_length=90)),
                ('is_announcement', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='hotel.community')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_community_channels', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subchannels', to='hotel.communitychannel')),
            ],
            options={
                'ordering': ['position', 'name'],
            },
        ),
        migrations.AddField(
            model_name='communitymessage',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='hotel.communitychannel'),
        ),
        migrations.CreateModel(
            name='CommunityModerationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=120)),
                ('action', models.CharField(choices=[('hold', 'Hold for review'), ('reject', 'Reject')], default='hold', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_rules', to='hotel.community')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('can_post', models.BooleanField(default=True)),
                ('can_create_threads', models.BooleanField(default=True)),
                ('can_pin', models.BooleanField(default=False)),
                ('can_moderate', models.BooleanField(default=False)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='hotel.community')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CommunityMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory_visible', models.BooleanField(default=True)),
                ('mentions_only', models.BooleanField(default=False)),
                ('muted_until', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='hotel.community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_memberships', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='hotel.communityrole')),
            ],
        ),
        migrations.AddConstraint(
            model_name='communitychannel',
            constraint=models.UniqueConstraint(fields=('community', 'slug'), name='unique_community_channel_slug'),
        ),
        migrations.AddConstraint(
            model_name='communitymoderationrule',
            constraint=models.UniqueConstraint(fields=('community', 'phrase'), name='unique_community_moderation_phrase'),
        ),
        migrations.AddConstraint(
            model_name='communityrole',
            constraint=models.UniqueConstraint(fields=('community', 'name'), name='unique_community_role_name'),
        ),
        migrations.AddConstraint(
            model_name='communitymembership',
            constraint=models.UniqueConstraint(fields=('community', 'user'), name='unique_community_membership'),
        ),
    ]
