# Generated by Django 5.2.5 on 2025-08-26 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor_name',
            field=models.CharField(default='Anonymous Seller', max_length=100),
        ),
    ]
