# Generated by Django 5.2.5 on 2025-08-28 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0005_product_video_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='video',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products/placeholder.jpg', upload_to='products/'),
        ),
    ]
