# Generated by Django 5.2.8 on 2025-11-16 15:26

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0009_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='product',
            name='negotiated_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='session_key',
            field=models.CharField(db_index=True, max_length=40, unique=True),
        ),
    ]
