# Generated by Django 5.2.8 on 2025-12-20 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0010_alter_cartitem_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='language_tag',
            new_name='country',
        ),
    ]
