# Generated by Django 5.2.8 on 2025-12-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0012_product_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('UGX', 'UGX (Ugandan Shilling)'), ('USD', 'USD (US Dollar)'), ('KES', 'KES (Kenyan Shilling)'), ('NGN', 'NGN (Nigerian Naira)'), ('GHS', 'GHS (Ghanaian Cedi)'), ('ZAR', 'ZAR (South African Rand)'), ('TZS', 'TZS (Tanzanian Shilling)'), ('RWF', 'RWF (Rwandan Franc)'), ('EGP', 'EGP (Egyptian Pound)')], default='UGX', max_length=3),
        ),
    ]
