# Generated by Django 5.2.8 on 2025-12-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0013_alter_product_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='referral_commission',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='The amount the vendor pays to the person who shared the link upon a successful sale.', max_digits=10),
        ),
    ]
