# Generated by Django 6.0.1 on 2026-01-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0015_remove_cartitem_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='affiliate_url',
            field=models.URLField(blank=True, help_text='Affiliate link to redirect buyers to external marketplace', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='external_id',
            field=models.CharField(blank=True, help_text='ID from external marketplace (e.g., AliExpress productId, Jumia SKU)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='Direct URL for images from external marketplaces', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='source',
            field=models.CharField(choices=[('local', 'Local Marketplace'), ('aliexpress', 'AliExpress'), ('jumia', 'Jumia')], default='local', help_text='Where this product originates from.', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
