# Generated by Django 6.0.1 on 2026-01-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0016_product_affiliate_url_product_external_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_synced',
            field=models.DateTimeField(auto_now=True, help_text='Last time this product was updated via API'),
        ),
        migrations.AlterField(
            model_name='product',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID from external marketplace (e.g., AliExpress productId, Jumia SKU)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='source',
            field=models.CharField(choices=[('local', 'Local Marketplace'), ('aliexpress', 'AliExpress'), ('jumia', 'Jumia')], db_index=True, default='local', help_text='Where this product originates from.', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('source', 'external_id'), name='unique_product_per_source'),
        ),
    ]
