# Generated by Django 6.0.1 on 2026-01-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0017_product_last_synced_alter_product_external_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='affiliate_url',
            field=models.TextField(blank=True, help_text='Affiliate link to redirect buyers to external marketplace', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.TextField(blank=True, help_text='Direct URL for images from external marketplaces', null=True),
        ),
    ]
