# Generated by Django 5.0.6 on 2026-08-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0018_alter_product_affiliate_url_alter_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('vehicles', 'Vehicles'), ('property', 'Property'), ('phones-tablets', 'Phones & Tablets'), ('electronics', 'Electronics'), ('home-furniture', 'Home, Furniture & Appliances'), ('fashion', 'Fashion'), ('beauty-personal-care', 'Beauty & Personal Care'), ('services', 'Services'), ('repair-construction', 'Repair & Construction'), ('commercial-tools', 'Commercial Equipment & Tools'), ('leisure-activities', 'Leisure & Activities'), ('babies-kids', 'Babies & Kids'), ('food-agriculture', 'Food, Agriculture & Farming'), ('hotel-budget', 'Simple Hotel Meals (3,000-10,000)'), ('hotel-1star', '1-Star Hotel Dining'), ('hotel-2star', '2-Star Hotel Dining'), ('hotel-3star', '3-Star Hotel Dining'), ('hotel-4star', '4-Star Hotel Dining'), ('hotel-5star', '5-Star Hotel Dining'), ('food-chips', 'Chips & Snacks'), ('food-burger', 'Burger & Fast Food'), ('food-pizza', 'Pizza & Oven Bakes'), ('food-rolex', 'Rolex & Street Rolls'), ('food-chicken', 'Chicken & Poultry'), ('food-fried-fish', 'Fried Fish & Seafood'), ('food-street-food', 'Street Food & Takeaway'), ('animals-pets', 'Animals & Pets')], db_index=True, default='', max_length=50),
        ),
    ]
