# Generated by Django 5.0.6 on 2026-09-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0022_order_buyer_confirmed_at_order_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='escrow_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('funded', 'Funds held in escrow'), ('released', 'Funds released'), ('disputed', 'Disputed')], db_index=True, default='pending', max_length=10),
        ),
    ]
