# Generated by Django 5.0.6 on 2026-09-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0024_affiliatepayout_payout_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('DZD', 'DZD (Algerian Dinar)'), ('AOA', 'AOA (Angolan Kwanza)'), ('BWP', 'BWP (Botswana Pula)'), ('BIF', 'BIF (Burundian Franc)'), ('CVE', 'CVE (Cape Verdean Escudo)'), ('XAF', 'XAF (Central African CFA Franc)'), ('KMF', 'KMF (Comorian Franc)'), ('CDF', 'CDF (Congolese Franc)'), ('DJF', 'DJF (Djiboutian Franc)'), ('ERN', 'ERN (Eritrean Nakfa)'), ('SZL', 'SZL (Eswatini Lilangeni)'), ('ETB', 'ETB (Ethiopian Birr)'), ('GMD', 'GMD (Gambian Dalasi)'), ('GHS', 'GHS (Ghanaian Cedi)'), ('GNF', 'GNF (Guinean Franc)'), ('KES', 'KES (Kenyan Shilling)'), ('LSL', 'LSL (Lesotho Loti)'), ('LRD', 'LRD (Liberian Dollar)'), ('LYD', 'LYD (Libyan Dinar)'), ('MGA', 'MGA (Malagasy Ariary)'), ('MWK', 'MWK (Malawian Kwacha)'), ('MRU', 'MRU (Mauritanian Ouguiya)'), ('MUR', 'MUR (Mauritian Rupee)'), ('MAD', 'MAD (Moroccan Dirham)'), ('MZN', 'MZN (Mozambican Metical)'), ('NAD', 'NAD (Namibian Dollar)'), ('NGN', 'NGN (Nigerian Naira)'), ('RWF', 'RWF (Rwandan Franc)'), ('STN', 'STN (Sao Tome and Principe Dobra)'), ('SCR', 'SCR (Seychellois Rupee)'), ('SLE', 'SLE (Sierra Leonean Leone)'), ('SOS', 'SOS (Somali Shilling)'), ('ZAR', 'ZAR (South African Rand)'), ('SSP', 'SSP (South Sudanese Pound)'), ('SDG', 'SDG (Sudanese Pound)'), ('TZS', 'TZS (Tanzanian Shilling)'), ('TND', 'TND (Tunisian Dinar)'), ('UGX', 'UGX (Ugandan Shilling)'), ('USD', 'USD (US Dollar)'), ('XOF', 'XOF (West African CFA Franc)'), ('ZMW', 'ZMW (Zambian Kwacha)'), ('ZWL', 'ZWL (Zimbabwean Dollar)'), ('EGP', 'EGP (Egyptian Pound)')], default='UGX', max_length=3),
        ),
    ]
