# Generated by Django 6.0.3 on 2026-03-28 13:18

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessReel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', cloudinary.models.CloudinaryField(help_text='Optimized for low-bandwidth delivery.', max_length=255, verbose_name='video')),
                ('thumbnail', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('caption', models.TextField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='UGX', max_length=10)),
                ('floor_price', models.DecimalField(blank=True, decimal_places=2, help_text='Absolute minimum the AI Agent can accept.', max_digits=12, null=True)),
                ('is_low_bandwidth_optimized', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trust_score', models.FloatField(default=0.0, help_text='Dynamic score (0-100) based on verified transactions.')),
                ('verified_deals_count', models.PositiveIntegerField(default=0)),
                ('is_verified_merchant', models.BooleanField(default=False, help_text='Awarded after AI assessment and identity verification.')),
                ('auto_negotiation_enabled', models.BooleanField(default=True, help_text='Enables the AI Agent to haggle on behalf of the user.')),
                ('minimum_margin_percent', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('bento_config', models.JSONField(blank=True, default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoEndorsement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_clip', cloudinary.models.CloudinaryField(max_length=255, verbose_name='video')),
                ('is_verified_transaction', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_endorsements', to=settings.AUTH_USER_MODEL)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_endorsements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
