# Generated by Django 6.0.3 on 2026-03-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_securemessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securemessage',
            name='content',
            field=models.TextField(),
        ),
    ]
