# Generated by Django 6.0.3 on 2026-03-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_alter_securemessage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessreel',
            name='currency',
            field=models.CharField(blank=True, default='UGX', max_length=10),
        ),
        migrations.AlterField(
            model_name='businessreel',
            name='floor_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Absolute minimum the AI Agent can accept. (Secret)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='businessreel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Public price. Leave blank for professional/work-sample content.', max_digits=12, null=True),
        ),
    ]
