# Generated by Django 6.0.3 on 2026-03-28 15:16

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_alter_businessreel_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businessreel',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='businessreel',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_reels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessreel',
            name='share_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='businessreel',
            name='share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
