# Generated by Django 6.0.3 on 2026-03-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_businessreel_download_count_businessreel_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialprofile',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text="Enter with country code (e.g., 256700000000). Used for 'Hire Me' / 'Order' buttons.", max_length=20, null=True),
        ),
    ]
