# Generated by Django 6.0.3 on 2026-03-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_socialprofile_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialprofile',
            name='trust_signature',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
