# Generated by Django 6.0.4 on 2026-04-09 13:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_socialprofile_trust_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessreel',
            name='video',
            field=cloudinary.models.CloudinaryField(help_text='Compressed to original width, max 5 minutes duration.', max_length=255, verbose_name='video'),
        ),
    ]
