# Generated by Django 5.0.6 on 2026-04-19 13:41

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_socialprofile_trust_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessreel',
            name='video',
            field=models.FileField(help_text='Stored on Cloudflare R2 for zero-egress high-speed delivery.', storage=django.core.files.storage.FileSystemStorage(), upload_to='africana_reels/'),
        ),
    ]
