# Generated by Django 5.0.6 on 2026-04-23 17:41

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_alter_businessreel_video'),
    ]

    operations = [
        # language and tags already exist in the production schema,
        # so only alter the video field in the database.
        migrations.AlterField(
            model_name='businessreel',
            name='video',
            field=cloudinary.models.CloudinaryField(help_text='Optimized for low-bandwidth delivery across Africa.', max_length=255, verbose_name='video'),
        ),
    ]
