# Generated by Django 5.0.6 on 2026-04-23 17:08
# This migration is empty because the 'language' and 'tags' columns
# already existed in the production database. Added to the model definition only.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_alter_businessreel_video'),
    ]

    operations = [
        # No operations - these fields already exist in production
    ]
