# Generated by Django 5.0.6 on 2026-04-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_alter_businessreel_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessreel',
            name='language',
            field=models.CharField(default='en', help_text='Content language code (e.g., \'en\', \'sw\', \'lg\')', max_length=10),
        ),
        migrations.AddField(
            model_name='businessreel',
            name='tags',
            field=models.TextField(blank=True, help_text='Comma-separated tags for content discovery'),
        ),
    ]
