# Generated by Django 5.0.6 on 2026-04-23 17:41

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_alter_businessreel_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessreel',
            name='language',
            field=models.CharField(default='en', help_text="Content language code (e.g., 'en', 'sw', 'lg')", max_length=10),
        ),
        migrations.AddField(
            model_name='businessreel',
            name='tags',
            field=models.TextField(blank=True, help_text='Comma-separated tags for content discovery'),
        ),
        migrations.AlterField(
            model_name='businessreel',
            name='video',
            field=cloudinary.models.CloudinaryField(help_text='Optimized for low-bandwidth delivery across Africa.', max_length=255, verbose_name='video'),
        ),
    ]
