# Generated by Django 5.2.13 on 2026-05-04 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_businessreel_language_businessreel_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businessreel',
            name='external_thumbnail_url',
            field=models.URLField(blank=True, help_text='External thumbnail URL for synced YouTube reels.', null=True),
        ),
        migrations.AddField(
            model_name='businessreel',
            name='external_video_url',
            field=models.URLField(blank=True, help_text='External video source URL for synced YouTube reels.', null=True),
        ),
        migrations.CreateModel(
            name='YouTubePartnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('daily_quota_used', models.PositiveIntegerField(default=0)),
                ('last_quota_reset', models.DateTimeField(auto_now_add=True)),
                ('partnership_description', models.TextField(blank=True, help_text='Why do you want to partner with us?')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='youtube_partnership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='YouTubeChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(help_text='YouTube Channel ID (e.g., UCxxxxxx)', max_length=100, unique=True)),
                ('channel_name', models.CharField(max_length=255)),
                ('channel_url', models.URLField(blank=True)),
                ('channel_thumbnail', models.URLField(blank=True, help_text='Channel avatar URL from YouTube')),
                ('is_syncing', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_frequency_hours', models.PositiveIntegerField(default=24, help_text='How often to check for new videos (in hours)')),
                ('total_videos_synced', models.PositiveIntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('partnership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='social.youtubepartnership')),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('partnership', 'channel_id')},
            },
        ),
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(help_text='YouTube Video ID', max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('thumbnail_url', models.URLField()),
                ('youtube_url', models.URLField()),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('youtube_views', models.PositiveIntegerField(default=0)),
                ('youtube_likes', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('business_reel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_youtube', to='social.businessreel')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='social.youtubechannel')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
