# Generated by Django 5.0.6 on 2026-06-04 11:17

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_businessreel_external_thumbnail_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessreel',
            name='cloudinary_public_id',
            field=models.CharField(blank=True, help_text='Cloudinary public ID for promoted viral content.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='businessreel',
            name='local_video',
            field=models.FileField(blank=True, help_text='Video stored on server disk (low-cost, handles initial uploads).', null=True, upload_to='reels/staging/'),
        ),
        migrations.AddField(
            model_name='businessreel',
            name='storage_tier',
            field=models.CharField(choices=[('LOCAL', 'Django Server Hard Drive'), ('CLOUDINARY', 'Cloudinary Global CDN')], default='LOCAL', help_text='Where this video is currently stored.', max_length=15),
        ),
        migrations.AddField(
            model_name='businessreel',
            name='views_count',
            field=models.PositiveIntegerField(default=0, help_text='Track views to trigger tier promotion to Cloudinary.'),
        ),
        migrations.AlterField(
            model_name='businessreel',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Optimized for low-bandwidth delivery across Africa.', max_length=255, null=True, verbose_name='video'),
        ),
    ]
