# Generated by Django 5.0.6 on 2026-08-03 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0013_youtube_channel_sync_error_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubevideo',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='youtubepartnership',
            name='user',
        ),
        migrations.RemoveField(
            model_name='youtubevideo',
            name='business_reel',
        ),
        migrations.DeleteModel(
            name='YouTubeChannel',
        ),
        migrations.DeleteModel(
            name='YouTubePartnership',
        ),
        migrations.DeleteModel(
            name='YouTubeVideo',
        ),
    ]
