# Generated by Django 5.0.6 on 2026-08-28 13:20

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0014_remove_youtubevideo_channel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessreel',
            name='local_video',
            field=models.FileField(blank=True, help_text='Video stored on server disk (low-cost, handles initial uploads).', null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='reels/staging/'),
        ),
    ]
