# Generated by Django 5.0.6 on 2026-09-09 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0024_affiliatepayout_payout_phone_and_more'),
        ('social', '0015_alter_businessreel_local_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessreel',
            name='creator_commission_percent',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='businessreel',
            name='shoppable_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shoppable_reels', to='eshop.product'),
        ),
    ]
