# Generated by Django 5.0.6 on 2026-09-09 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0026_promotioncampaign'),
        ('social', '0017_nativeinvoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='socialprofile',
            name='business_registration_ref',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='socialprofile',
            name='national_id_last4',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='socialprofile',
            name='verification_status',
            field=models.CharField(default='unsubmitted', max_length=20),
        ),
        migrations.AddField(
            model_name='socialprofile',
            name='verification_tier',
            field=models.CharField(choices=[('none', 'Not verified'), ('local_maker', 'Verified Local Maker'), ('hub_resident', 'Hub Resident'), ('top_seller', 'Top Seller')], default='none', max_length=20),
        ),
        migrations.CreateModel(
            name='BrowserPushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(unique=True)),
                ('subscription', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='browser_push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MerchantAnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('product_view', 'Product view'), ('reel_view', 'Reel view'), ('cart_add', 'Cart add'), ('checkout', 'Checkout'), ('sale', 'Sale')], max_length=20)),
                ('visitor_key', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_analytics_events', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', to='eshop.product')),
                ('reel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', to='social.businessreel')),
            ],
        ),
    ]
